export const globalConstants = {
  ADD__ACADEMIES: "ADD__ACADEMIES",
  REMOVE__ACADEMIES: "REMOVE__ACADEMIES",
  EDIT__ACADEMIES: "EDIT__ACADEMIES",
  UPDATE__ACADEMYDETAILS: "UPDATE__ACADEMYDETAILS",
};
